[package]
name = "segment_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = {version = "1.0", features = ["derive"]}
anyhow = "1.0"
bincode = {version = "1.3"}

[dev-dependencies]
rstest = "0.26.1"
rand = "0.8"
